version: '3.8'

services:
  ubuntu-dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ubuntu-dev
    platform: linux/amd64
    volumes:
      - ./workspace:/workspace
    tty: true